### ISSUE TITLE
How to play?

### ISSUE THREAD

**Issue by D3VONT3CH** [forairan/Ogar#10]
I installed and configured all correctly, but when i open the website of game only this appears:

https://server-d3vont3ch.c9.io/index.html

what i need to do?

i used this command:

````
node Ogar --master --game
````

and this appeared:

````
[Master] Listening on port 8080
[Game] Listening on port 3000
[Game] Current game mode is Free For All
````

**Comment by D3VONT3CH** [comment]
Solved, but i can't use this:
https://github.com/DnAp/Agar.io-Reverse-Engineering
?

**Comment by vram4** [comment]
The master server is usable at the moment, just run the game server and connect to it via client mods.

**Comment by D3VONT3CH** [comment]
thank you.
