### ISSUE TITLE
The length of x and y are changed.

### ISSUE THREAD

**Issue by dimotsai** [forairan/Ogar#100]
Does anyone notice that the client side script has been updated? The length of x and y became 4 bytes, instead of original 2 bytes.

https://github.com/forairan/Ogar/blob/master/src/packet/UpdateNodes.js#L55-L56

**Comment by joery1337** [comment]
@dimotsai That's a weird change, why would x or y ever get higher as 65535, lol.

**Comment by Ephemerality** [comment]
They also reduced the mouse coordinates to Int16s, to reduce packet size I assume.  
If they are willing to sacrifice another 4 bytes per cell, they must be planning to increase map size soon, possibly a new mode or something.  
Commit 29ec3a4ba0a29bddd94ccb93365cf255661ac5c9 *should* work with the latest client, assuming I didn't miss anything.
