### ISSUE TITLE
Uncaught RangeError: Offset is outside the bounds of the DataView

### ISSUE THREAD

**Issue by MarcoPL66** [forairan/Ogar#102]
![image](https://cloud.githubusercontent.com/assets/13303335/8639450/dcecea52-28da-11e5-894e-746539c022a8.png)
(10 errors per second) (I named myself Marco but this happens)

**Comment by vram4** [comment]
Are you using the latest server update? There were some packet changes

**Comment by robt44** [comment]
im having the same problem

**Comment by Mapzilla** [comment]
I have the same problem and I redownloaded the server about 3 hours ago because of this, so i don't think it is a problem with the version

**Comment by robt44** [comment]
I had problems with the old version then I installed the new version and still had them it was working fine yesterday, what happened

**Comment by Mapzilla** [comment]
I can try redownloading again i guess

**Comment by Mapzilla** [comment]
Nope still doesnt work, maybe it has to do with bots i usually play with 10

**Comment by vram4** [comment]
Are you using the windows binary?

**Comment by TTGTRE** [comment]
I'm having this same issue.

I get this error when I join the server with default configurations.

This happens on (index):400

Here's an image: http://gyazo.com/27e49bac301652418d7343ffd08a3664

**Comment by Ephemerality** [comment]
Again, make sure you're using the latest version and the official client on agar.io. If they aren't both up to date, the packet structure won't match.

**Comment by TTGTRE** [comment]
I'm using agar.io to play agar.io, and I'm using the server which I downloaded less than an hour ago. Any other suggestions?

**Comment by subv3rsion** [comment]
Per @Ephemerality's suggestion, please ensure you're using the latest version of the code (not the binary -- I haven't seen a specification of what anyone's using here). The binaries are not yet up to date, and in fact are being moved to a different location so that we can automate the process in the very, very near future.
The binaries that were out of date have been removed roughly 40 minutes ago, and hopefully an update will be present soon.

**Comment by CameronRedGem** [comment]
This seems to be my problem like the range isn't coming up correct and also the names that are being typed right in. (yes its the latest)

**Comment by Mapzilla** [comment]
So windows doesn't work

**Comment by Ephemerality** [comment]
New binaries will be uploaded soon. In the meantime you could always install Node and ws to run it without the binary.

**Comment by Mapzilla** [comment]
OK  i think i can wait but I wonder how long that will be

**Comment by robt44** [comment]
great now it wont even load https://cloud.githubusercontent.com/assets/13303982/8651692/7523f780-2948-11e5-87a8-8151d85a27e7.png

**Comment by TTGTRE** [comment]
@robt44 That's your fault dude.

**Comment by Ephemerality** [comment]
It can't be run with the batch file at the moment unless you compile the binary yourself; the binary has been removed from the repo. A download for it will be available soon.

**Comment by vram4** [comment]
You get that error because the binary was removed, hence the "system cannot find the path specified". Please wait until we prepare a proper download.
