### ISSUE TITLE
This is possible?

### ISSUE THREAD

**Issue by mafiakb** [forairan/Ogar#103]
Hi, one question.

Is possible add border at virus or cell?

![border](https://cloud.githubusercontent.com/assets/12769609/8640252/6478e8dc-28b7-11e5-9372-b2e5f051e747.png)

**Comment by Ephemerality** [comment]
Not without changing the client. Your only options from the server side are round or spiky.

**Comment by Agarian** [comment]
lol i referenced the wrong issue

**Comment by Andrews54757** [comment]
Actually, there might be a way. Just like skins. But i am too lazy to look through main_out.js in agar.io
