### ISSUE TITLE
Unable to move in Ogar server.

### ISSUE THREAD

**Issue by NNickey** [forairan/Ogar#105]
I can't seem to move the character at all on my hosted Ogar server?

I am hosting local, and not using hamachi.

Alt + C = "ws://127.0.0.1:443"

All ports are forwarded DMZ, no luck.

http://gyazo.com/29f4020301514bbf6b196d170833ee60

**Comment by Ephemerality** [comment]
Make sure you're updated to commit cdb49eaab22728daef8f57f50ba6db7fbf8f9366  
Packet structure in the client changed again.

**Comment by NNickey** [comment]
Quick reply. Thank you!

**Comment by BlazeGaming** [comment]
I can't move either do I download the stuff from the link?

**Comment by vram4** [comment]
Yes, download from http://dl.ogarproject.com/ for the latest executable version of Ogar.

**Comment by BlazeGaming** [comment]
Downloaded that already.

**Comment by BlazeGaming** [comment]
So what else do I do?
