### ISSUE TITLE
Problem Zombie Mode

### ISSUE THREAD

**Issue by Chumachos** [forairan/Ogar#108]
Hello, I have a problem before configurate my private server in Zombie Mode (gamemode 12)
When I play in my server, I can't see anythhing, only this:

![error](https://cloud.githubusercontent.com/assets/13316561/8652230/e071d31a-297d-11e5-985e-65f440198099.png)

I have changed the gamemode, to play in gamemode 0, but I saw the same that in gamemode 12.
Before deleting the folder, and creating another server, the problem persists.

Can anyone help me?
Thank you for read

**Comment by Ephemerality** [comment]
Any errors in the JavaScript console in the browser? Are you using the official agar.io client?

**Comment by Chumachos** [comment]
In the console there aren't any errors. I'm using the client downloaded here:
https://github.com/vram4/Ogar

**Comment by Chumachos** [comment]
In the console there aren't any errors. I'm using the client downloaded here:
https://github.com/vram4/Ogar

**Comment by Ephemerality** [comment]
The server from there you mean? Should be using the latest on this repo (https://github.com/forairan/Ogar) and connecting straight from agar.io.

**Comment by Chumachos** [comment]
I can't start the server downloaded on this link you sent me

![](http://i.gyazo.com/21f1891f052f6369c4ce38597d3bcb74.png)
. The problem is the system can't find the  route specified

**Comment by Ephemerality** [comment]
It can't be run with the batch file at the moment unless you compile the binary yourself; the binary has been removed from the repo. A download for it will be available soon.  
The one you downloaded on the other link works, but it is not updated.

**Comment by Chumachos** [comment]
The version not updated works fine before I configure on Zombie Mode. What can I do to play again without problems?

**Comment by BenCat07** [comment]
download the new version
