### ISSUE TITLE
ERROR 

### ISSUE THREAD

**Issue by robozeri** [forairan/Ogar#109]
Uncaught RangeError: Offset is outside the bounds of the DataView
PLEASE RESOLV

**Comment by subv3rsion** [comment]
Please search for an issue before creating a new one in the future.

This issue has already been resolved. The binaries have not been updated, and are in the process of being automated.
I'd recommend download the source and running it manually: https://github.com/forairan/Ogar#obtaining-and-using

**Comment by robozeri** [comment]
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-042stab108.5
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "./Ogar"
npm ERR! cwd /root/serveragario
npm ERR! node -v v0.10.4
npm ERR! npm -v 1.2.18
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/serveragario/npm-debug.log
npm ERR! not ok code 0
 this is error

**Comment by forairan** [comment]
That's not a full error stack trace - we need the full content of the error text to help.

**Comment by robozeri** [comment]
this is complete error
npm install ./Ogar
npm http GET https://registry.npmjs.org/ws
npm http 304 https://registry.npmjs.org/ws
npm ERR! Error: No compatible version found: ws@'^0.7.2'
npm ERR! Valid install targets:
npm ERR! ["0.2.6","0.2.8","0.2.9","0.3.0","0.3.1","0.3.2","0.3.3","0.3.4","0.3.4-2","0.3.5","0.3.5-2","0.3.5-3","0.3.5-4","0.3.6","0.3.7","0.3.8","0.3.9","0.4.0","0.4.1","0.4.2","0.4.3","0.4.5","0.4.6","0.4.7","0.4.8","0.4.9","0.4.10","0.4.11","0.4.12","0.4.13","0.4.14","0.4.15","0.4.16","0.4.17","0.4.18","0.4.19","0.4.20","0.4.21","0.4.22","0.4.23","0.4.24","0.4.25","0.4.27","0.4.28","0.4.29","0.4.30","0.4.31","0.4.32","0.5.0","0.6.0","0.6.1","0.6.2","0.6.3","0.6.4","0.6.5","0.7.0","0.7.1","0.7.2"]
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:685:10)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:607:10
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-042stab108.5
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "./Ogar"
npm ERR! cwd /root/serveragario

**Comment by Ephemerality** [comment]
Looks like you need to run `npm install ws` first.  
AFAIK you don't even have to `npm install ./Ogar` as long as you run the `npm install ws` command from the directory where you have Ogar...
