### ISSUE TITLE
DataView error

### ISSUE THREAD

**Issue by pSkpt** [forairan/Ogar#11]
I install node.js and ws. Setup my server. Everything okey but i look browser console while i was playing.

This error : 

Uncaught RangeError: Offset is outside the bounds of the DataView

repeat count : 560

**Comment by vram4** [comment]
Use the source in my fork: https://github.com/vram4/Ogar . I have that issue fixed already.

**Comment by pSkpt** [comment]
@vram4 thank you. :)

**Comment by electronoob** [comment]
That fix is really helpful, I guess quite obviously, I have your code running on 2 servers at the moment at usa.agariomods.com:1234 and europe.agariomods.com:443 and it's exciting to know that we are reaching closer to an open agario server.

**Comment by D3VONT3CH** [comment]
thnk you, now i can use without this bug.

**Comment by sasanikolic90** [comment]
What was the fix here? The repo linked above is not online anymore.
