### ISSUE TITLE
 Uncaught RangeError: Offset is outside the bounds of the DataView

### ISSUE THREAD

**Issue by villezpa** [forairan/Ogar#115]
When im connectin to my server .. im getting this

38(index):400 Uncaught RangeError: Offset is outside the bounds of the DataViewzb @ (index):400yb @ (index):396wb @ (index):396
(index):399 Uncaught RangeError: Offset is outside the bounds of the DataViewzb @ (index):399yb @ (index):396wb @ (index):396
19(index):400 Uncaught RangeError: Offset is outside the bounds of the DataView

Uncaught RangeError: Offset is outside the bounds of the DataView

**Comment by BenCat07** [comment]
me too get the new server!

just came out 3h ago

**Comment by BenCat07** [comment]
but i don't know how to start the new server

**Comment by vram4** [comment]
If you are using the windows binary, the latest version is now hosted at http://dl.ogarproject.com/
