### ISSUE TITLE
Not able to run as easy as the instructions state in Windows 8.1

### ISSUE THREAD

**Issue by NNickey** [forairan/Ogar#117]
![screenshot_20](https://cloud.githubusercontent.com/assets/3466265/8708608/48b68f38-2afa-11e5-8bf4-1a52f4641ef7.png)

Unless you are using the windows binary.

Only works after "npm install ws"

**Comment by quonic** [comment]
From your screenshot, you are trying to run the node.js code with nodejs. For it to run you have to install the "ws" module. Usually with ```npm install ws```

Else look in the bin folder and run that.

**Comment by vram4** [comment]
> Unless you are using the windows binary.
> 
> Only works after "npm install ws"

It only works after "npm install ws" because you were **NOT** using the windows binary. The binary files can be found at http://dl.ogarproject.com/
