### ISSUE TITLE
Dies instantly or Glitches, freezes?

### ISSUE THREAD

**Issue by Seanray29** [forairan/Ogar#118]
Whenever i join my server nothing is shown but the grid lines. the screen shakes crazy and my cell looks weird like its being squished or i instantly die like i was devoured. this is the best i can descirbe, you may not understand but if you had the same probelm and fixed it or you know how to please, let me know!

**Comment by Ephemerality** [comment]
Do you have the latest version? If you are just using Ogar.exe make sure you get the latest from http://dl.ogarproject.com/

**Comment by maixuanhan** [comment]
Yeh, I faced that problem. Because your client is too old or your server is too old. The latest version of this server is compatible with latest *agar.io* client.

**Comment by subv3rsion** [comment]
^

**Comment by Seanray29** [comment]
Awesome! thanks guys
