### ISSUE TITLE
Grid Fail w/ name

### ISSUE THREAD

**Issue by CameronRedGem** [forairan/Ogar#119]
Hello,

I tried to use the new files of Ogar.exe and seem like the grid couldn't load right at all (also the grid would be shaking and have nothing to show). With that even saying, I am also seeing that the name list isn't coming up correctly. 

![screenshot 23](https://cloud.githubusercontent.com/assets/13305790/8713481/0e6cfa14-2b37-11e5-9f3a-1217a13388a7.png)

**Comment by Gayans101** [comment]
I have the same problem

**Comment by Ephemerality** [comment]
Something is out of date somewhere. If you have the latest version of Ogar, try turning any mods off or running in Igcognito mode.

**Comment by CameronRedGem** [comment]
^ Still not the case or an answer for my problem still.

**Comment by loko987bg** [comment]
How to fix this i have the same problem
Please Help

**Comment by quonic** [comment]
What browser are you using? Chrome, Firefox, IE? We need information to help diagnose your issue.

**Comment by CameronRedGem** [comment]
i using chrome just because of the ip address plugin

**Comment by nicklasblomb** [comment]
I have the same problem

**Comment by nicklasblomb** [comment]
![udklip](https://cloud.githubusercontent.com/assets/13389750/8760355/7f8cc7ce-2d17-11e5-8fd6-15f9e2516f3d.PNG)

**Comment by nicklasblomb** [comment]
its start doing this
![udklip](https://cloud.githubusercontent.com/assets/13389750/8760361/da3acd9c-2d17-11e5-960f-a9f9e66150d2.PNG)

**Comment by nicklasblomb** [comment]
![udklip](https://cloud.githubusercontent.com/assets/13389750/8760381/e344c720-2d18-11e5-8885-8c67c5af5446.PNG)

**Comment by vram4** [comment]
@CameronRedGem Try removing that ip connect mod and connect from the dev console in your browser. That mod is probably whats breaking your game.

@nicklasblomb You dont have the latest version, in your case, it was the server, the newest versions of Ogar are hosted [here](http://dl.ogarproject.com/)

**Comment by nicklasblomb** [comment]
Dev console?

**Comment by nicklasblomb** [comment]
Now it just doing this
![udklip](https://cloud.githubusercontent.com/assets/13389750/8760497/163a7456-2d21-11e5-8edb-d77304eae032.PNG)

**Comment by PackmanHunter** [comment]
@nicklasblomb I have the same problem and i solve it i make a tutoriel : https://youtu.be/hitH4_8bykg ;)

**Comment by Ephemerality** [comment]
You "solved"  it by running the exe and connecting? There are better tutorials at https://www.youtube.com/channel/UCyGKd1y64ly5wrjGFpcq5SA anyway.

**Comment by Ephemerality** [comment]
Press F12 and go to console to get to the JavaScript console.

**Comment by Youtubrer** [comment]
Same thing is happening to me. I have the latest version, and it still wants to suicide.

**Comment by vram4** [comment]
@Youtubrer If youre using Windows, the latest version can be found at http://dl.ogarproject.com/

**Comment by Youtubrer** [comment]
@vram4 yes, i have the latest version, according to 7 minutes ago.

**Comment by vram4** [comment]
@Youtubrer Are you also using the official client at agar.io ?

**Comment by Youtubrer** [comment]
@vram4 Yea, im pretty sure.

**Comment by Youtubrer** [comment]
@vram4 i have disabled all mods, and everything else.

**Comment by Youtubrer** [comment]
Do i have to download the source, or everything else with it, or just the EXE?

**Comment by vram4** [comment]
@Youtubrer It works fine on my computer, what is the full name of the file you downloaded? Ex. "Ogar-windows-68f746c.exe"

**Comment by Youtubrer** [comment]
Ogar-windows-68f746c.exe, yea

**Comment by Youtubrer** [comment]
Windows 7, originally for xp, compatible with vista

**Comment by Youtubrer** [comment]
67.42.109.29:443 is the IP for the server

**Comment by Ephemerality** [comment]
Port must not be forwarded or you took it down, connection fails.

**Comment by Youtubrer** [comment]
huh, because, i just forwarded it a minute ago (7) and the server is up...

**Comment by Youtubrer** [comment]
TCP &UDP Is the one i fowarded

**Comment by Ephemerality** [comment]
Check http://www.canyouseeme.org/ for port 443.

**Comment by Youtubrer** [comment]
Ok, it appears to be working now

**Comment by Ephemerality** [comment]
Yep, it's up, though it seems like the config is a bit messed up.

**Comment by Youtubrer** [comment]
So i should reset the config? Thats what i tried before

**Comment by Youtubrer** [comment]
![capture](https://cloud.githubusercontent.com/assets/13411787/8770398/f17c8316-2e65-11e5-85d1-48d34ba31c7f.PNG)
The Tampermonkey extension is disabled.

**Comment by vram4** [comment]
@Youtubrer What are you clicking to launch Ogar? The file named "Ogar-windows-68f746c", right?

**Comment by Youtubrer** [comment]
Yes.
![capture2](https://cloud.githubusercontent.com/assets/13411787/8770454/18994064-2e67-11e5-956d-d9dc0a1454ce.PNG)

**Comment by vram4** [comment]
@Youtubrer Can you press "CTRL + F5" on your keyboard while you are on the agar.io page? This will force refresh your client and clear the cache.

**Comment by Youtubrer** [comment]
Still no errors relating to the "Help im stuck in a wall" Problem.

**Comment by Youtubrer** [comment]
although the error still exists...

**Comment by vram4** [comment]
Can you copy/paste your entire config here?

**Comment by Youtubrer** [comment]
serverMaxConnections = 64
serverPort = 443
serverGamemode = 0
serverBots = 0
serverViewBaseX = 1024
serverViewBaseY = 592
serverStatsPort = 88
serverStatsUpdate = 60
serverLogLevel = 1
borderLeft = 6000
borderRight = 6000
borderTop = 6000
borderBottom = 6000
spawnInterval = 20
foodSpawnAmount = 10
foodStartAmount = 100
foodMaxAmount = 500
foodMass = 1
virusMinAmount = 10
virusMaxAmount = 50
virusStartMass = 100
virusFeedAmount = 7
ejectMass = 12
ejectMassLoss = 16
ejectSpeed = 160
ejectSpawnPlayer = 50
playerStartMass = 10
playerMaxMass = 22500
playerMinMassEject = 32
playerMinMassSplit = 36
playerMaxCells = 16
playerRecombineTime = 30
playerMassDecayRate = 0.002
playerMinMassDecay = 9
playerMaxNickLength = 15
playerDisconnectTime = 60
tourneyMaxPlayers = 12
tourneyPrepTime = 10
tourneyEndTime = 30
tourneyTimeLimit = 20
tourneyAutoFill = 0
tourneyAutoFillPlayers = 1

**Comment by vram4** [comment]
> borderLeft = 6000
> borderRight = 6000
> borderTop = 6000
> borderBottom = 6000

Your border values are wrong, they specify the coordinates of the outer edge of the border. So, with your current config, you would have an effective area of 0. Try this instead:
borderLeft = 0
borderRight = 6000
borderTop = 0
borderBottom = 6000

This will make a 6000x6000 size map

**Comment by Youtubrer** [comment]
oh. Before when i had it in the correct config, it didnt do anything diffrent, thanks for the help!

**Comment by CameronRedGem** [comment]
Thank you for fixing my problem as well with that exe. Sorry I been away on camp since 7/19 and now gotten back
