### ISSUE TITLE
flood of spikes

### ISSUE THREAD

**Issue by electronoob** [forairan/Ogar#12]
I don't have any data for you unfortunately, but happy to do a tcpdump or something else at your request.

I notice and it seems to be when everyone has disconnected from the server, a client makes a fresh connection there is a megafuckton of spikes everywhere and the game goes a big crazy at that point.

**Comment by vram4** [comment]
Are you using the latest source? There were issues with the game client freezing up every few seconds, but i fixed that already.

**Comment by electronoob** [comment]
yep I updated when I saw your pull request had been merged:
https://github.com/forairan/Ogar/commit/7de66dd263c3b17fc03031953a0d535271d94ff5

**Comment by electronoob** [comment]
I haven't been able to reproduce it again by myself, but the two servers I run here at usa.agariomods.com:1234   and   europe.agariomods.com:443 are publically known and some other event may have occurred between me reconnecting.

**Comment by vram4** [comment]
Okay, so did you get any of these issues after you updated the server?

**Comment by electronoob** [comment]
yes

**Comment by vram4** [comment]
I'm going to look into it then.

**Comment by electronoob** [comment]
Awesome, if there's anything at all I can do to help, let me know.

**Comment by D3VONT3CH** [comment]
we need a client to play without agar.io

**Comment by electronoob** [comment]
@D3VONT3CH 
The issue tracker isn't a forum for idle chit-chat.

**Comment by vram4** [comment]
I pushed an update on my fork that should fix this issue. In case you were wondering, it was caused by multiple large cells eating multiple viruses at the same time. It took me a while before i was actually able to recreate this consistently, which is why the fix took so long.

**Comment by electronoob** [comment]
Understandable, thank you and I will update my servers shortly. Nice job.
