### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by KariyakiLP** [forairan/Ogar#123]
Add a feature to frezze players

and for spliting Players
and for combine players
and for remove the bots!

**Comment by vram4** [comment]
What do you mean by freezing, splitting, combining players? If you want to split a player, you could just shoot a virus into them. Bots can aslo be configured so they dont spawn, they're turned off by default anyways.

**Comment by missionrulz** [comment]
Looks like the same as https://github.com/forairan/Ogar/issues/134. Could probably close this.
