### ISSUE TITLE
I have an awkward glitch/idk

### ISSUE THREAD

**Issue by Vravinite** [forairan/Ogar#124]
When i open the server everything seems alright BUT when i join it there's like no space or i spawn outside of map. http://i.imgur.com/L6SeX2H.png

**Comment by vram4** [comment]
If you are on windows, please make sure you are using the latest binary file from dl.ogarproject.com . If you are already, can you post your config file here?

**Comment by Vravinite** [comment]
I guess i wasn't, it is just open it and install and well open server right?

**Comment by Vravinite** [comment]
Ah yea it works now thanks!
