### ISSUE TITLE
How to Specify Team color in Team mode?

### ISSUE THREAD

**Issue by helma27** [forairan/Ogar#126]
Just like the title, how to do it?
Thank you

**Comment by vram4** [comment]
The function for setting team colors can be found at ```Teams.prototype.getTeamColor``` in src/gamemodes/teams.js

**Comment by helma27** [comment]
is there any php code that i can use to specify it?

**Comment by vram4** [comment]
This is the function you need to replace (includes some comments) in src/gamemodes/teams.js. The return value is a JSON that defines the red,green,blue value of the color.
```javascript
Teams.prototype.getTeamColor = function(team) {
    // Gets the base color of the current team
    var color = this.colors[team];
    // Constructs a color json object
    return {
        // Each value is randomized a bit so not all colors of the people on the same team are identical
        r: this.fuzzColorComponent(color.r),
        b: this.fuzzColorComponent(color.b),
        g: this.fuzzColorComponent(color.g)
    };
};
```
If you want to add/edit the base team colors, go to:
``` javascript
    this.colors = [
        {'r': 223, 'g': 0, 'b': 0}, // Client Red Team
        {'r': 0, 'g': 223, 'b': 0}, // Client Green Team
        {'r': 0, 'g': 0, 'b': 223}, // Client Blue team
    ]; // Make sure you add extra colors here if you wish to increase the team amount [Default colors are: Red, Green, Blue]
```
in the same file (src/gamemodes/teams.js).

**Comment by helma27** [comment]
@vram4 thanks, that was i looking for :D 
Umm.. i have more question, what should i edit to call it from main page if i use own client?
I'am using @Eureka22  agar-client, and @m-byte for master server, and @forairan server
Sorry for a lot of asking...

**Comment by vram4** [comment]
If youre using agar-clone, look for:
```javascript 
teamColor = ["#333333", "#FF3333", "#33FF33", "#3333FF"],
```
in main_out.js (use find).

The 2nd value in the array is the red color, 3rd is green, and 4th is blue.
