### ISSUE TITLE
The option to remove added bots

### ISSUE THREAD

**Issue by z3ntu** [forairan/Ogar#127]
If this is already in Ogar, I did not find that option.

EDIT: Or generally kick players.

**Comment by missionrulz** [comment]
You can kill players, which is essentially the same. Unless you are wanting to forcefully disconnect them (their client will appear frozen).

**Comment by missionrulz** [comment]
You could just change 'serverBots' to 0 in gameserver.ini

I have a working command like this on my server, will create a merge request later today/tomorrow.

**Comment by Ephemerality** [comment]
Added in 023d08d9f0bfbaf36ab1543b3bd0d9ded451876f.
