### ISSUE TITLE
Not Implemented Error

### ISSUE THREAD

**Issue by faurest** [forairan/Ogar#13]
Hello, i have installed Ogard on my Debian 7 x64 Server and when i go on the port :443 i have a "Not Implemented Error".

How i can fix it ?

Best Regards,
iTouch

**Comment by vram4** [comment]
127.0.0.1:443 is the IP you connect to with your client, not with your browser. To connect properly, you can get a client side mod that allows you to connect to servers via ip, like the one at agariomods.com. Or you can join an official game with the vanilla client first, then open up dev console and type "connect("ws://localhost:443")".
