### ISSUE TITLE
when i command npm install ./Ogar

### ISSUE THREAD

**Issue by Ganggroid** [forairan/Ogar#132]
When i command npm install ./Ogar,
There is no response.
![image](https://cloud.githubusercontent.com/assets/5188404/8769843/0796d3a6-2ee1-11e5-8440-851b8e1ebb0b.png)

**Comment by vram4** [comment]
Did you use ```git clone git://github.com/forairan/Ogar.git Ogar``` first?

**Comment by helma27** [comment]
Mr. @vram4 can you help me in issue #126 ?

**Comment by Ganggroid** [comment]
@vram4 yes. i did it.

**Comment by Ganggroid** [comment]
@vram4 
![image](https://cloud.githubusercontent.com/assets/5188404/8770016/98505edc-2ee4-11e5-9ed1-f100e21015cf.png)

**Comment by Ephemerality** [comment]
If Node is already installed, you should just be able to run `npm install ws` and then `node Ogar` all within that folder.

**Comment by Ganggroid** [comment]
@Ephemerality ..
![image](https://cloud.githubusercontent.com/assets/5188404/8770039/e475abd2-2ee4-11e5-90b0-c80ee54d1f80.png)

**Comment by Ganggroid** [comment]
I don't know well

**Comment by vram4** [comment]
What version of nodejs do you have?

**Comment by Ganggroid** [comment]
@vram4 v0.6.19 sir.

**Comment by vram4** [comment]
@Ganggroid Youre going to want to update to the latest version of [nodejs](https://nodejs.org/download/) then.

**Comment by Ganggroid** [comment]
@vram4 I'm using Raspberry-Pi. when i apt-get install nodejs, no any update.

**Comment by Ganggroid** [comment]
@vram4 Thanks sir.
