### ISSUE TITLE
Ideas 

### ISSUE THREAD

**Issue by KariyakiLP** [forairan/Ogar#134]
No , I mean when you type the command addbot can not remove these bots purpose there should be a Command . And there should be a split command to split players , because you can not spawn exactly the player the virus . With Frezze I mean that the selected player can not move until it was eaten or with a unfrezze command again to move . example :

freeze [ playerid ]

unfrezze [ playerid ]

And another idea for TP

Man should so TP can :

tp [ 1PLAYERID ] [ 2PLAYERID ]

Here is the 1 to be the player of Teleportet .

and is 2 hinteleportet for the player where 1 .

Sorry for the lousy English translator Google . Greetings from Germany

**Comment by vram4** [comment]
Ah, that makes more sense, but most of the commands were made to help me test/debug new features, not to let admins harass players. I will probably add these in later though, probably in Ogar 2.

**Comment by missionrulz** [comment]
I have implemented the freeze & split commands on my server, will update with merge request later today/tomorrow.
