### ISSUE TITLE
How to edit cell speed?

### ISSUE THREAD

**Issue by Charlo74** [forairan/Ogar#135]
Hi, how to edit cell speed? thx

**Comment by vram4** [comment]
If youre not using the windows binary, go to src/entity/cell.js and look at
```javascript
Cell.prototype.getSpeed = function() {
    return 30 * Math.pow(this.mass, -1.0 / 4.5) * 50 / 40;
};
```

**Comment by ZombieMIW** [comment]
What about with windows binary?

**Comment by ZombieMIW** [comment]
or where do we download the cell.js?

**Comment by illinoisjackson** [comment]
@ZombieMIW I got a pull request merged that added the playerSpeed option to gameserver.ini, changing player speed is a lot easier now
