### ISSUE TITLE
Thanks, and i have an error when i connet!

### ISSUE THREAD

**Issue by Ganggroid** [forairan/Ogar#138]
![image](https://cloud.githubusercontent.com/assets/5188404/8775214/152fa20a-2f21-11e5-8cb2-a3f0e537c236.png)
![image](https://cloud.githubusercontent.com/assets/5188404/8775221/2640e0fe-2f21-11e5-91ee-913c3f6906d8.png)

What should i do for this error?????
Huhhhh...

**Comment by Ephemerality** [comment]
Not entirely sure how you have things to set up, but it seems odd. If you are trying to run it from your own hosted version of the client, it won't work anyway unless you modified the source to allow it...

**Comment by Ganggroid** [comment]
@Ephemerality so,.. what should i do for fix this error?
Need server set? or..

**Comment by Ganggroid** [comment]
![image](https://cloud.githubusercontent.com/assets/5188404/8775409/fa39624a-2f22-11e5-92f2-6b61bd778ce6.png)
I'm using raspberrypi, Apache2

**Comment by Ephemerality** [comment]
Are you trying to play the game from your Raspberry Pi as well or are you using your computer? If you're on your computer you need to put your Pi's IP, not `127.0.0.1`...

**Comment by Ganggroid** [comment]
@Ephemerality Uh.. web server and game server are same...

**Comment by Ganggroid** [comment]
Only one piserver

**Comment by Ephemerality** [comment]
My question wasn't where the server was though, where are you playing the game? If you are loading the game on your computer, but the server is on your Pi, you can't use 127.0.0.1.

**Comment by Ganggroid** [comment]
@Ephemerality Oh! Thanks
I will try!
Thank you! I'm happpppyyyyyyyyy!
