### ISSUE TITLE
Game freezing & Ghost player

### ISSUE THREAD

**Issue by Ariamiro** [forairan/Ogar#14]
sometimes the game are freezing, and i can see a ghost player.

**Comment by vram4** [comment]
I fixed the issue with "ghost players", cells will now disappear after the player disconnects in my latest update on my fork. The freezing client was fixed in yesterday's update. Perhaps you had an older version?

**Comment by dogeangel** [comment]
that happens sometimes only on all the types of tablets
 so ok that happens where you playing agario on a tablet
