### ISSUE TITLE
Kicked players cell does not get killed

### ISSUE THREAD

**Issue by z3ntu** [forairan/Ogar#140]
Just tested it out with the newest version.

**Comment by Ephemerality** [comment]
Fair point. Updated in 13d01952b07918667c1d9a6015550f1f517330a4.  
I figured it should act like when someone leaves; their cells sit there just waiting to be eaten.  
Makes sense that if you're purposely kicking someone that they should disappear, though.

**Comment by z3ntu** [comment]
Ah okay, thank you!

**Comment by riyuk** [comment]
Ejected Mass did not disappear. Should it?

**Comment by z3ntu** [comment]
I don't think that ejected mass technically belongs to a player...

**Comment by Ephemerality** [comment]
No, ejected mass is treated the same as food. It doesn't belong to a player (until they nomnomnom it of course).
