### ISSUE TITLE
Bot names do not get loaded

### ISSUE THREAD

**Issue by z3ntu** [forairan/Ogar#141]
Running Ubuntu Server 15.04, newest software. I also tried changing the permissions for the file 777 (Readable, Writeable & Executable for everyone). Still "bot1", "bot2" etc

**Comment by Ephemerality** [comment]
The botnames.txt needs to be in the same folder as your gameserver.ini (the folder you run the game from).  
For example, if you run the game with `node Ogar` it needs to be in the same spot as the Ogar folder.

**Comment by z3ntu** [comment]
I just cloned the git repo... 
This is my folder:
```
total 56
drwxr-xr-x  4 root root 4096 Jul 20 15:02 .
drwx------ 12 root root 4096 Jul 20 09:08 ..
drwxr-xr-x  8 root root 4096 Jul 20 15:13 .git
-rw-r--r--  1 root root  678 Jul 19 09:28 .gitignore
-rw-r--r--  1 root root 1440 Jul 19 09:28 CONTRIBUTING.md
-rw-r--r--  1 root root  554 Jul 19 09:28 LICENSE.md
-rw-r--r--  1 root root 5870 Jul 20 15:02 README.md
-rwxrwxrwx  1 root root  357 Jul 19 09:28 botnames.txt
-rw-r--r--  1 root root 2646 Jul 19 09:30 gameserver.ini
-rwxr-xr-x  1 root root 5187 Jul 20 15:02 ogar-linux-script.sh
-rw-r--r--  1 root root  575 Jul 19 09:28 package.json
drwxr-xr-x  7 root root 4096 Jul 20 15:02 src
```

**Comment by Ephemerality** [comment]
What command are you using to start the game?

**Comment by z3ntu** [comment]
`node Ogar` from the "main directory"

**Comment by Ephemerality** [comment]
Yeah, so your botnames and gameserver.ini need to be in that main directory (one up from the dir listing you posted). Or you could `cd Ogar` and then `node src`.

**Comment by z3ntu** [comment]
With `node src` in the Ogar directory it works... Either update the README.md or make it that it chooses the right directory!

**Comment by helma27** [comment]
if your Installation of Ogar on '/root/Ogar'
Then you should put your botnames.txt at '/root/*heres your botnames.txt'
