### ISSUE TITLE
I can't get it started

### ISSUE THREAD

**Issue by abandoncaptain** [forairan/Ogar#142]
C:\Users\[]\Desktop\Ogar-master\src>node index.js
'node' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\[]\Desktop\Ogar-master\src>pause
Press any key to continue . . .

how do i fix this?

**Comment by z3ntu** [comment]
You have to install node.js ...

**Comment by abandoncaptain** [comment]
C:\Users\[]\Desktop\Ogar-master\src>node index.js
module.js:338
    throw err;
          ^
Error: Cannot find module 'ws'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (C:\Users\[]\Desktop\Ogar-master\src\GameServer.j
s:2:17)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

C:\Users\[]\Desktop\Ogar-master\src>pause
Press any key to continue . . .

How do i fix this? I installed node.js and this is what i get.

**Comment by Ephemerality** [comment]
`npm install ws`

**Comment by abandoncaptain** [comment]
what do u mean?

**Comment by z3ntu** [comment]
Enter that in cmd

**Comment by abandoncaptain** [comment]
ok thank you, i've got it all setup and i have a port forward for it and now when i try to connect to it it brings me to a random server.

**Comment by z3ntu** [comment]
How do you "try to connect"?

**Comment by abandoncaptain** [comment]
i would do agar.io/?[my ip]:25566 and agar.io/?[my ip]:88

**Comment by abandoncaptain** [comment]
i tried both and they just brought me to a random server

**Comment by z3ntu** [comment]
http://agar.io?ip=[your-IP]:[your-port]
Or enter the following in the browser console:
`javascript:connect("ws://[your-IP]:[your-port]","");`

**Comment by abandoncaptain** [comment]
thx so much i got it to work. do u want to join me?

**Comment by z3ntu** [comment]
no thank you.
