### ISSUE TITLE
Failure to connect to the server.

### ISSUE THREAD

**Issue by NikoCodex** [forairan/Ogar#144]
Hello, i am currently trying to make my own version of Agar.io located at http://blobeatblob.cf/ however i am failing to connect to the server as i get the result http://prntscr.com/7v082u
This has worked fine on localhost, however as moving on a VPS it fails entirely.
Help would be appreciated, thank you.

**Comment by Ephemerality** [comment]
See commit 0000e51fcd45ff8f48eb77890c1d8f0ee917339f.

**Comment by NikoCodex** [comment]
Thank you, works perfectly now :+1:

**Comment by Ephemerality** [comment]
Keep in mind that by removing that code, you might be committing copyright infringement.

**Comment by Youtubrer** [comment]
@NikoCodex How did you host it on a website?

**Comment by NikoCodex** [comment]
Not to worry Ephemerality, got that under control.
Youtubrer, i got a VPS, then i got the agar.io client clone and ogar.
Setting it up was easy.

**Comment by Youtubrer** [comment]
@Ephemerality Shouldn't hosting it on your own site help Agar.io, because agar.io is getting the money?
