### ISSUE TITLE
Brothers can't join

### ISSUE THREAD

**Issue by TheBlueWizard** [forairan/Ogar#145]
Hi, I finally have my server working. but my little brothers can't join. they got an error about something illegal or something(look at screenshot). Please help, it took so much time before it finally worked.
Thanks
![schermopname 1](https://cloud.githubusercontent.com/assets/13433140/8798715/a5e7743e-2fa4-11e5-8929-2104730e8672.png)

**Comment by hotdogman** [comment]
change `connect("ws://172.16.10.42.443")` to `connect("ws://172.16.10.42.443", "")`

**Comment by z3ntu** [comment]
@hotdogman Please a : before the 443 ...
