### ISSUE TITLE
Client

### ISSUE THREAD

**Issue by bky6677** [forairan/Ogar#146]
Current Can not we find a suitable web client to the server version?
Sory bad english.

**Comment by Ephemerality** [comment]
http://agar.io

**Comment by bky6677** [comment]
I want to enter the name of another domain.

**Comment by z3ntu** [comment]
I don't really know what you want to ask... Can you try to explain it a bit more?

**Comment by Janmm14** [comment]
Well you can make a simple html - js combination. create a frameset with one frame ( http://agar.io ) and use bodie's onload to execute ´´´connect("ws://your.ip:port")´´´

**Comment by Ephemerality** [comment]
The server specifically blocks connections coming from domains other than agar.io, at the request of the Agar.io developer. We don't support setting up a personally-hosted client.

**Comment by jollesnaas** [comment]
I can help u with that: Contact me on skype: jolle.snaas1

or make it yourself with a cheap VPS:
You can rent a VPS (Windows or Linux) of me: 4 euro/month/512MB RAM or 8 euro/month/1GB RAM, 20 euro/Year/512MB RAM or 40 euro/year/1GB RAM.

If you want to know more or order, please contact me on skype: jolle.snaas
*Free test included!

**Comment by Andrews54757** [comment]
i dont trust this . dont fall for it others! Only give money to trusted people
