### ISSUE TITLE
Lag causes character to spaz out and jump across screen fast

### ISSUE THREAD

**Issue by Spurlex** [forairan/Ogar#16]
Video: http://file.spurlex.com/1k4KC/4YfPiPpQ

This is caused by the client slightly lagging and then it builds up and starts to bounce around at extreme speeds.

**Comment by vram4** [comment]
In the recent update, Zeach, the main dev of agar.io, has added code to the client that allows it to "guess" where its going. The problem is that if you lag and miss packets, the client will think you are still moving and try to compensate for that hence the extreme movement.
