### ISSUE TITLE
When I'm ate, I'm still here

### ISSUE THREAD

**Issue by Toumaniere** [forairan/Ogar#26]
But I can't play. When I split my cell and when I go back in one celle, I grow up but my second cell is still here and it doesn't disappear.
http://i.gyazo.com/d68084cbacf10782f0b39381d3f1f195.gif

Plus, I have this error, I think there is a link with agar.io..
http://i.gyazo.com/500efe03610cf879ce4fef3fc5cfcbf3.png

**Comment by vram4** [comment]
Please update to the latest version on my fork if you want to use with the latest client: https://github.com/vram4/Ogar
