### ISSUE TITLE
It does not work in linux

### ISSUE THREAD

**Issue by listenyoumusic** [forairan/Ogar#33]
but i installed mono and wine but I can not get it to work

Why no compatibility to Linux

Ty :)

sorry for my english I'am Spanish

**Comment by vram4** [comment]
You need to install node.js and its ws module and run from src

**Comment by listenyoumusic** [comment]
It's my first time working with node.js
if you are so kind
commands to tell me that I should proceed

thanks again

**Comment by listenyoumusic** [comment]
Ok i works 

ty :+1:

**Comment by vram4** [comment]
@listenyoumusic I will be compiling a linux (and mac) version soon when i get the chance, so you wont have to deal with node.js
