### ISSUE TITLE
10% Eating Rule

### ISSUE THREAD

**Issue by atenefyr** [forairan/Ogar#34]
If I understand correctly, the determining factor for i-eat-you-or-you-eat-me is "if the mass of one player is 10% or more than the player they collided with, they eat that player". In Ogar, this is done rather like "if the mass of one player is more than the mass of another player, they eat that player" (for me a bot with just one more mass than me can eat me).

**Comment by vram4** [comment]
No, its 25% in both ogar and vanilla. If you have a small amount of mass (below 20), then it just takes a few more mass to eat you. In addition, mass is shown a little inaccurate beacuse of the packet structure and math logic. You may notice this when youre eating food  with a large cell and your mass is not going up. (This happens in vanilla too)
