### ISSUE TITLE
The virus can be eaten and disconnect peoples.

### ISSUE THREAD

**Issue by Killy85** [forairan/Ogar#37]
When a virus is too much fed, the cell just eats it, grows a lot and players around are disconnected (or kicked ?). Here is what I edited in `gameserver.ini`, to see if it comes from our server configuration.

`
borderLeft = 0 
borderRight = 9000
borderTop = 0
borderBottom = 9000
spawnInterval = 4
foodSpawnAmount = 15
foodStartAmount = 150
foodMaxAmount = 1500
foodMass = 5
virusMinAmount = 8
virusMaxAmount = 80
virusStartMass = 200
virusBurstMass = 150
ejectMass = 16
ejectMassGain = 12
ejectSpeed = 400
playerMinMassEject = 10
playerMinMassSplit = 3
playerMinMassDecay = 9
`

**Comment by vram4** [comment]
virusStartMass needs to be lower than virusBurstMass. playerMinMassEject needs to be higher than ejectMass.

**Comment by Killy85** [comment]
OK. It can be good to add warnings for those kind of problems.

**Comment by natinusala** [comment]
Good idea, when you start the server it checks for bad configuration and warns in the console
