### ISSUE TITLE
Hub thingys (experimental) don't spawn on large border maps.

### ISSUE THREAD

**Issue by Jackster35** [forairan/Ogar#48]
This is the border settngs for our maps:

borderLeft = 0
borderRight = 12500
borderTop = 0
borderBottom = 12500

It would seem they don't spawn or at least not as often. Worth taking a look? :)

**Comment by vram4** [comment]
@Jackster35 Viruses/Mother cells dont spawn unless there is an empty spot in the map. Maybe too many people were big and the game couldnt find a suitable spot?

**Comment by Jackster35** [comment]
When we reboot, not many would use it. We've remove Experimental and dedicated those 3 servers we had to coping with more FFA.
