### ISSUE TITLE
Can't install (linux)

### ISSUE THREAD

**Issue by flaxues** [forairan/Ogar#49]
Hello

I wanted to install this on linux ubuntu 15.04

but i get this error:

http://pastebin.com/XdxvJ9Zr

**Comment by Ephemerality** [comment]
From the looks of it, you tried to install it to a directory that doesn't exist yet (which the script should possibly handle I suppose). If you can't get it working, the manual install instructions in the readme should work as well.

**Comment by flaxues** [comment]
i'm already things for a hour

**Comment by flaxues** [comment]
Manual installation:

http://pastebin.com/445csHAF

**Comment by Ephemerality** [comment]
Are you running the commands with 'sudo'?

**Comment by flaxues** [comment]
Yes

**Comment by kensukekita** [comment]
i installed it on an ubuntu server on the last version 15.04 i had the same issue i installed it by this way

./ogar-linux-script.sh install ../ and it works but now i dont know how to run it lol

**Comment by techpulse** [comment]
i also have issue installing, tried to run ogar via node and it gave some error

**Comment by flaxues** [comment]
I only have linux vps

**Comment by flaxues** [comment]
so really annoying :(

**Comment by techpulse** [comment]
im using windows fine, but windows isn't up to date.. :(

**Comment by flaxues** [comment]
It's just windows is using much resources and not that stable...

**Comment by Jackster35** [comment]
I have a site that has 800 active players daily. We run all our servers (14 of them) on Debian 8 (Linux) and they're run beautifully. Linux has the upper hand in this sort of area, just saying.

**Comment by techpulse** [comment]
where did you get your servers from Jackster?

**Comment by Jackster35** [comment]
Current players: 752 Max players: 943

All our servers are from ovh.com but have dedicated servers with 32GB of RAM, with 8 Xeon Core setup running around 3 VPS' on them at 4GB

**Comment by Jackster35** [comment]
One of our dedicated servers: http://i.imgur.com/beJio5l.png

You will need more CPU power than RAM

**Comment by techpulse** [comment]
Okay, i have a vps from ovh too had no issue with windows nor cpu.. only got 1 core * 3.7 GHz xeon

and 2GB ram windows, works damn fine.. i want linux since that one is updated with (reload commands) etc.. how did you install it exactly? i had issues doing so.

**Comment by Jackster35** [comment]
http://i.imgur.com/tiKKChL.png

Err, okay hang on I'll reply with a small tutorial

**Comment by techpulse** [comment]
Have you had any issues with people complaining regarding lagging/spikes? 

I had, i believe it's their location as I'm hosted in France and most are from USA. Or can it be the windows app?

**Comment by Jackster35** [comment]
> apt-get install screen git
> wget https://github.com/taaem/nodejs-linux-installer/releases/download/v0.3/node-install.sh -O node-install.sh && chmod +x node-install.sh && ./node-install.sh
> adduser agar
> su - agar
> git clone https://github.com/forairan/Ogar.git
> cd Ogar/
> nodejs index.js

That should work, let me know.

**Comment by techpulse** [comment]
Thank you, are there any way to run several under different ports too like windows? im giving it a shot now, gonna intsall a new vps

**Comment by techpulse** [comment]
root@agar7:/home/admin# wget https://github.com/taaem/nodejs-linux-installer/releases/download/v0.3/node-install.sh -O
wget: option requires an argument -- 'O'
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.

**Comment by techpulse** [comment]
agar@agar7:~/Ogar$ node index.js
module.js:338
    throw err;
          ^
Error: Cannot find module '/home/agar/Ogar/index.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by flaxues** [comment]
I get the same error.

**Comment by techpulse** [comment]
also from what i see you didnt run the install script, i tried to do so but it's messing up with the permissions since i added a root user agar.

**Comment by flaxues** [comment]
So i cd in the src file now i get this error


module.js:340
    throw err;
          ^
Error: Cannot find module 'ws'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/agar/Ogar/src/GameServer.js:2:17)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by flaxues** [comment]
Techpulse index.js is in src directory

**Comment by Jackster35** [comment]
My bad, in the agar user, run this:

npm install ws

**Comment by flaxues** [comment]
Installing it...

**Comment by flaxues** [comment]
[Game] Ogar - An open source Agar.io server implementation

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EACCES
    at errnoException (net.js:901:11)
    at Server._listen2 (net.js:1020:19)
    at listen (net.js:1061:10)
    at Server.listen (net.js:1135:5)
    at GameServer.startStatsServer (/home/agar/Ogar/src/GameServer.js:897:21)
    at GameServer.start (/home/agar/Ogar/src/GameServer.js:192:10)
    at Object.<anonymous> (/home/agar/Ogar/src/index.js:25:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by Jackster35** [comment]
Change the port in gameserver.ini that's in the Ogar folder. I believe that's the error for it.

**Comment by flaxues** [comment]
i installed it and did nodejs index.js

**Comment by flaxues** [comment]
ok i'm changit it

**Comment by flaxues** [comment]
same error

**Comment by vram4** [comment]
EACCES means youre not running with root privileges, type  "sudo -s" before you run Ogar

**Comment by flaxues** [comment]
vram i will try it

**Comment by Jackster35** [comment]
vram4, it's probably because he's binding to 443. If you bind higher than 1024 I believe it is, you don't need root. I recommend 1501-1509. It's what we use so we don't have to use root for our servers and keeps it clean I guess.

**Comment by flaxues** [comment]
it's working thnx @Jackster35 and @vram4

**Comment by vram4** [comment]
@Jackster35 That could be it too

**Comment by sonicwolfsdutch** [comment]
im getting 
agar@vps-4630:~/Ogar$ node Ogar
module.js:338
    throw err;
          ^
Error: Cannot find module '/home/agar/Ogar/Ogar'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by Ephemerality** [comment]
`cd ..` then `node Ogar`

**Comment by sonicwolfsdutch** [comment]
ohh that was stupid xD dint see it oops thx anyway it works 
now do u guys know a alternative ip? i have a domain name could i get it like Ogar.domainname.com  or domainname.com/ogar ?

**Comment by PineapplePuncher** [comment]
Last login: Thu Oct 29 17:20:19 on ttys000
Stevans-MacBook-Pro:~ stevanperrino$ /Users/stevanperrino/Desktop/Ogar-master/src/Start.command ; exit;
module.js:339
    throw err;
    ^

Error: Cannot find module '/Users/stevanperrino/index.js'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:134:18)
    at node.js:961:3
/Users/stevanperrino/Desktop/Ogar-master/src/Start.command: line 2: pause: command not found
logout

[Process completed]

Can someone please tell me what I can do to fix this!?
thank you.
