### ISSUE TITLE
Random freezing

### ISSUE THREAD

**Issue by Andrew5545** [forairan/Ogar#51]
Has Im playing on my server with bots I suddenly freeze and have to rejoin the server, note the server isnt crashing cause the bots etc are still on it playing I just randomly freeze so do my friends even with out bots we do.
I made the server today. 6/30/2015
Here is a video of what happens.  Ignore the webcam in the bottom right I didn't realize it was on.
https://drive.google.com/file/d/0B2E4entgyGxPQWdfRFVLcThwNmM/view?usp=sharing
thats what happens.  Thats not a photo im zooming in and out on thats the game and what happens

**Comment by vram4** [comment]
Are you using the latest version?

**Comment by Jackster35** [comment]
Yes, sir! :)

**Comment by Andrew5545** [comment]
Yes Got it today

**Comment by Andrew5545** [comment]
Does anyone know why this happens

**Comment by vram4** [comment]
Does it say anything in the server console?

**Comment by Andrew5545** [comment]
Nothinge

**Comment by Andrew5545** [comment]
The game still runs Like I can join back, and the bots will be moveing

**Comment by Jackster35** [comment]
Sounds client side

**Comment by vram4** [comment]
@Jackster35 Nah, these kinds are freezes are caused by the server terminating the connection to the client, but the client doesnt know its been disconnected, so it freezes. As for why it happens, either there was an error sending a packet (which would have caused an error message) or a possible memory leak was about to occur with your socket.

**Comment by Andrew5545** [comment]
@vram If somethings broken its with my computer. XD

**Comment by Jackster35** [comment]
I've recently started having this issue too with some users. The server will randomly kill the connection, unsure as to why.

**Comment by Jackster35** [comment]
I've found the issue and reported it to vram4. If you want a hotfix remove this from Virus.js:

if ((endMass > 3000) && (numSplits > 0)) {
        bigSplits++;
        numSplits--;
    }

until vram4 comes out with a fix. :)

**Comment by Ephemerality** [comment]
So the extra big split is the issue?

**Comment by Jackster35** [comment]
That's what I found in my testing.

**Comment by Andrew5545** [comment]
Woow Im not the only one

**Comment by Andrew5545** [comment]
@Jackster35 Ive been crashing when small to or split a lot of times

**Comment by Ephemerality** [comment]
What were the conditions, was it you that got split on the virus, did it freeze you or others? I've been trying it out and haven't had any issues when I split at 3001+ mass.

**Comment by Andrew5545** [comment]
No Just when we slip a lot with the space key about 5 sec later we froze and only us, the server kept running just you froze everyone else was still on etc

**Comment by techpulse** [comment]
ive not had any issues my self

**Comment by Ephemerality** [comment]
Just to add to this one, I've been having random freezing issues on my test servers as well (Mac OS 10.10.x). It would only occur after typing a command in the console, usually after doing a playerlist. The client would stay connected and if I typed on the console, the client would start receiving updates again until I stopped typing.
