### ISSUE TITLE
Disable commands

### ISSUE THREAD

**Issue by techpulse** [forairan/Ogar#52]
How can I disable commands, or make them executable by only a specific user?

I'm using it on linux. Hosting private server for my site, but don't want everyone to access the commands.. grr

**Comment by Jackster35** [comment]
Remove them your self from https://github.com/forairan/Ogar/blob/master/src/modules/CommandList.js

**Comment by techpulse** [comment]
oh looks easy, how can i add so only specific user or ip can use them? =)

**Comment by vram4** [comment]
Only whoever that has access to the server console can use the commands, so not just anyone. If you want to disable them anyways, start up ogar with the "--noconsole" arguement.

**Comment by techpulse** [comment]
i am hosting them on a VPS, i want so only my IP can use it (not the vps ip, but mine)

**Comment by techpulse** [comment]
cheers for all the help though didnt know it was this active

**Comment by vram4** [comment]
It should be fine as long as no one else has access to that vps
