### ISSUE TITLE
Reload not working

### ISSUE THREAD

**Issue by techpulse** [forairan/Ogar#54]
Reload not working in Windows.

command not found

**Comment by vram4** [comment]
Yeah, because the windows binary is not updated to the latest version yet.

**Comment by techpulse** [comment]
Ah okay, any idea when it will be?

**Comment by vram4** [comment]
Probably when i find a fix for the random freezes

**Comment by techpulse** [comment]
I've had no issues, running on windows 2012 server other than someone say they lag spike (idk if thats their latency or what?)
