### ISSUE TITLE
Multi core support?

### ISSUE THREAD

**Issue by joery1337** [forairan/Ogar#55]
Hey,

Will Ogar support multiple cores in the future? Just curious because I've multi core servers but Ogar is not taking advantage of that.

**Comment by Jackster35** [comment]
Nodejs isn't multi-threaded so there will not be a fix, but we use JXNode, Which has built in multi-thread support out of the box. (It's a fork of NodeJS) I recommend you use that. We have around 700-800 users daily and it holds pretty well between 14 servers. I recommend it! ;)

**Comment by joery1337** [comment]
@Jackster35 thanks! With node it was extremely laggy.
