### ISSUE TITLE
client

### ISSUE THREAD

**Issue by flaxues** [forairan/Ogar#56]
How can i add my own client so i don't need to go to agar.io to join my server?

**Comment by Jackster35** [comment]
https://github.com/Eureka22/agar-clone

**Comment by flaxues** [comment]
Thnx again another question how can i chat when i write a message and click on enter nothing shows up ...

**Comment by helma27** [comment]
@flaxues use this Server https://github.com/Eureka22/Ogar

**Comment by flaxues** [comment]
Thnx everyone for helping me i got everything working :+1:
