### ISSUE TITLE
Vram4 ?

### ISSUE THREAD

**Issue by forumapp28** [forairan/Ogar#59]
http://prntscr.com/7ns5uw
http://prntscr.com/7ns8t4

See pictures.

Can you fix ?

**Comment by vram4** [comment]
Someone is purposely trying to crash your server. I would look into that if i were you.

**Comment by forumapp28** [comment]
Can you fix ?

**Comment by forumapp28** [comment]
Sorry bad english

**Comment by vram4** [comment]
Okay, but dont spam me with issues next time
