### ISSUE TITLE
Botlist and ini files have no line breaks

### ISSUE THREAD

**Issue by Creeperman8362** [forairan/Ogar#63]
These files have no line breaks, its all one line, and word wrap just makes it a bunch of jumbled text.
![agar1](https://cloud.githubusercontent.com/assets/8520072/8487983/97fccb88-20c4-11e5-8d42-892765635890.png)
![agar2](https://cloud.githubusercontent.com/assets/8520072/8487982/97899564-20c4-11e5-9071-f67ca24e1602.png)
![agar3](https://cloud.githubusercontent.com/assets/8520072/8487981/97865e8a-20c4-11e5-9cca-d54a105c4ab1.png)
![agar4](https://cloud.githubusercontent.com/assets/8520072/8487980/97861aa6-20c4-11e5-9aa0-c4c598becb86.png)

**Comment by Jackster35** [comment]
They're UNIX encoding. You're reading it as windows. Convert it via notepad++, it'll work.

**Comment by vram4** [comment]
Use something other than the default notepad.

**Comment by Creeperman8362** [comment]
pasting it into pastebin and back into notepad fixes it ?
