### ISSUE TITLE
Nicknames are different than read in console?

### ISSUE THREAD

**Issue by SacredMike** [forairan/Ogar#66]
![Bug](http://i.imgur.com/SMimg1y.png)

**Comment by SacredMike** [comment]
Update: It's not ran on names anymore.. It's what number you are. For example if you are the only person in the game you are number 1. If you add bots they will be 2-(amount of bots.) Hope you understand that

**Comment by vram4** [comment]
Because of people who use special characters/spaces in their name, commands that target players now use player id. You can get player's ids by using the "playerlist" command.
