### ISSUE TITLE
Can't Connect

### ISSUE THREAD

**Issue by BenCat07** [forairan/Ogar#69]
i can't connect i always getting the error ERR_NAME_NOT_RESOLVED i tried to use my ip and localhost connection but it won't work :(
![image](https://cloud.githubusercontent.com/assets/13179138/8508900/52ea4bd4-2285-11e5-85ed-5ed3ecf54b05.png)

**Comment by vram4** [comment]
You have the wrong syntax, try: 
```connect("ws://127.0.0.1:443","a");```

**Comment by BenCat07** [comment]
thanks i works now :D

**Comment by mirage1993** [comment]
thanks!!!
solved!
