### ISSUE TITLE
Consideration for moving to JXNode?

### ISSUE THREAD

**Issue by Jackster35** [forairan/Ogar#75]
Has there ever been thought about coding it for JXNode? JXNode is essential NodeJS but multithreaded and optimized.

We use it and it runs amazing, but I'm sure using some of their functions could smoother it a lot more!

More info here: http://jxcore.com/home/

**Comment by vram4** [comment]
Everything will be converted to jxnode functions when i have time in the private repo

**Comment by Jackster35** [comment]
Okay cool man :)
