### ISSUE TITLE
Cant bind port even if i change it in gameserver.ini

### ISSUE THREAD

**Issue by Adryd** [forairan/Ogar#78]
when i try to start ogar using node Ogar it crashes and gives me this:

[Game] Ogar - An open source Agar.io server implementation
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at Server.listen (net.js:1267:5)
    at GameServer.startStatsServer (/Users/Adryd/Ogar/src/GameServer.js:919:21)
    at GameServer.start (/Users/Adryd/Ogar/src/GameServer.js:206:10)
    at Object.<anonymous> (/Users/Adryd/Ogar/src/index.js:25:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
[Error] Server could not bind to port! Please close out of Skype or change 'serverPort' in gameserver.ini to a different number.

the port that i set it to is not used by any other services
ive changed to port multiple times to random numbers but it didnt do anything either

OS = Mac OS X 10.10.4

**Comment by Jackster35** [comment]
In the directory of which you try to start it, do "ls" and tell me your output.

**Comment by Ephemerality** [comment]
Make sure you're changing serverStatsPort in the config and that it's the config in the directory you launch the game from (the source comes with several for some reason).

**Comment by maixuanhan** [comment]
Yes, It's the stat-server, `GameServer.startStatsServer (/Users/Adryd/Ogar/src/GameServer.js:919:21)`, default config as port **88**, I don't see any advantage of that server right now. The statistics information also looks not updated when I press F5.

**Comment by Ephemerality** [comment]
It is supposed to update every minute (or serverStatsUpdate in the config). It's currently being used by Agariomods to provide a private server listing.  
Are you sure it's getting changed in the right config? I have it running on my MacBook (Yosemite) and changing the stats port works here. `[Game] Loaded stats server on port 667`  
If you set the port to 0 in the config, it should not load the stats server at all.

**Comment by Adryd** [comment]
The ogar directory for me is /Users/Adryd/Ogar
i use sudo node Ogar to start and the log is:
[Game] Ogar - An open source Agar.io server implementation
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at Server.listen (net.js:1267:5)
    at GameServer.startStatsServer (/Users/Adryd/Ogar/src/GameServer.js:919:21)
    at GameServer.start (/Users/Adryd/Ogar/src/GameServer.js:206:10)
    at Object.<anonymous> (/Users/Adryd/Ogar/src/index.js:25:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
[Error] Server could not bind to port! Please close out of Skype or change 'serverPort' in gameserver.ini to a different number.

the port is set to 25564 ive tried many different ports and i changed both the main port and the stats port (the stats port is 25563)

**Comment by vram4** [comment]
Can i see your entire config?

**Comment by Adryd** [comment]
// Ogar configurations file
// Lines starting with slashes are comment lines

// [Server]
// serverGamemode: 0 = FFA, 1 = Teams, 2 = Experimental, 10 = Tournament, 11 = Hunger Games
// serverBots: Amount of player bots to spawn (Experimental)
// serverViewBase: Base view distance of players. Warning: high values may cause lag
// serverStatsPort: Port for the stats server. Having a negative number will disable the stats server.
// serverStatsUpdate: Amount of seconds per update for server stats
// serverLogLevel: Logging level of the server. 0 = No logs, 1 = Logs the console, 2 = Logs console and ip connections
serverMaxConnections = 64
serverPort = 25564
serverGamemode = 2
serverBots = 0
serverViewBaseX = 1024
serverViewBaseY = 592
serverStatsPort = 25563
serverStatsUpdate = 60
serverLogLevel = 1

// [Border]
// Border values of the map (Vanilla values are left/top = 0, right/bottom = 11180.3398875)
borderLeft = 0
borderRight = 6000
borderTop = 0
borderBottom = 6000

// [Spawn]
// Each interval is 1 tick (50 ms)
spawnInterval = 20
foodSpawnAmount = 10
foodStartAmount = 100
foodMaxAmount = 1000
foodMass = 1
virusMinAmount = 10
virusMaxAmount = 50
virusStartMass = 100
virusFeedAmount = 7

// [Ejected Mass]
// ejectMass: Mass of ejected cells
// ejectMassLoss: Mass lost when ejecting cells
// ejectSpeed: Base speed of ejected cells
// ejectSpawnPlayer: Chance for a player to spawn from ejected mass
ejectMass = 12
ejectMassLoss = 16
ejectSpeed = 160
ejectSpawnPlayer = 50

// [Player]
// playerRecombineTime: Base amount of ticks before a cell is allowed to recombine (1 tick = 1000 milliseconds)
// playerMassDecayRate: Amount of mass lost per tick (Multiplier) (1 tick = 1000 milliseconds)
// playerMinMassDecay: Minimum mass for decay to occur
// playerDisconnectTime: The amount of seconds it takes for a player cell to be removed after disconnection (If set to -1, cells are never removed)
playerStartMass = 10
playerMaxMass = 22500
playerMinMassEject = 32
playerMinMassSplit = 36
playerMaxCells = 16
playerRecombineTime = 30
playerMassDecayRate = .002
playerMinMassDecay = 9
playerMaxNickLength = 15
playerDisconnectTime = 60

// [Gamemode]
// Custom gamemode settings
// tourneyTimeLimit: Time limit of the game, in minutes.
// tourneyAutoFill: If set to a value higher than 0, the tournament match will automatically fill up with bots after value seconds
// tourneyAutoFillPlayers: The timer for filling the server with bots will not count down unless there is this amount of real players
tourneyMaxPlayers = 12
tourneyPrepTime = 10
tourneyEndTime = 30
tourneyTimeLimit = 20
tourneyAutoFill = 0
tourneyAutoFillPlayers = 1

**Comment by quonic** [comment]
Adryd if you run ```netstat -an``` then that should show you what ports are being used.

**Comment by Adryd** [comment]
i know theres nothing running on the port i did that before i posted here

**Comment by Ephemerality** [comment]
And you're definitely modifying the gameserver.ini that is in the folder where your Ogar folder is, right? Not the one in src or the one in Ogar. (since you're launching it using node Ogar)

**Comment by maixuanhan** [comment]
@Ephemerality : hi, I see that there are too many issues with port number. Why don't you guys modify the output code of EADDINUSE error.
```javascript
[Error] Server could not bind to port! Please close out of Skype or change 'serverPort' in gameserver.ini to a different number.
```
==> 
```javascript
[Error] Server could not bind to port: <PORT_NUMBER here>. Please read the README carefully.
```

**Comment by Adryd** [comment]
yes i am sure im moddifying it in the ogar folder. i changed both to make sure

**Comment by vram4** [comment]
@maixuanhan I could add that, but some people dont even read the entire error message.

**Comment by CameronRedGem** [comment]
Well that is their problem if they don't read the entire message

**Comment by SamHep0803** [comment]
I changed the server port to 25565 and server stats to 25564
