### ISSUE TITLE
Listen to two ports

### ISSUE THREAD

**Issue by techpulse** [forairan/Ogar#79]
I changed port on linux one to 443 and another one to 1337, for some reason I can't listen to another port while running another ogar..

[root@centos-agar src]# node index.js
[Game] Ogar - An open source Agar.io server implementation
Error: listen EADDRINUSE
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1043:14)
    at listen (net.js:1065:10)
    at Server.listen (net.js:1139:5)
    at GameServer.startStatsServer (/home/admin/HackForums/Ogar/src/GameServer.js:919:21)
    at GameServer.start (/home/admin/HackForums/Ogar/src/GameServer.js:206:10)
    at Object.<anonymous> (/home/admin/HackForums/Ogar/src/index.js:25:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
[Error] Server could not bind to port! Please close out of Skype or change 'serverPort' in gameserver.ini to a different number.

**Comment by Jackster35** [comment]
Probably have apache or nginx running. :x

**Comment by techpulse** [comment]
No. Running 443 works fine, 1337 one on other hand isn't .. worked fine on windows

**Comment by Jackster35** [comment]
What's the output for:

netstat -tulpn | grep 1337

**Comment by techpulse** [comment]
Nothing.

**Comment by techpulse** [comment]
[root@centos-agar src]# netstat -tulpn | grep 443
tcp        0      0 0.0.0.0:443                 0.0.0.0:*                   LISTEN      1581/node

**Comment by Jackster35** [comment]
So 443 is already in use.

pkill node

then try running it again.

**Comment by techpulse** [comment]
dude i said 1337 dont work, but 443 works lol

**Comment by Jackster35** [comment]
How is it listening when it errors with Error: listen EADDRINUSE

When that occurs it kills it self. You're not telling me everything.

**Comment by techpulse** [comment]
I already explained the issue, listening to another port at once doesn't work. I assume it's because the stats server are listening on port 88.

**Comment by Jackster35** [comment]
...

Do me a favour and set your game port to 1501 and stats port to 1601. You might not have so much issues -_-

**Comment by techpulse** [comment]
to be honest i didnt even know there was any stats port lol i guess if thats in the config.. then my issue is solved

**Comment by Jackster35** [comment]
Yes, there's a stats port.

**Comment by techpulse** [comment]
does it not contain like top players etc?

**Comment by Jackster35** [comment]
One of my servers: http://i.imgur.com/Ik4ib99.png

**Comment by Jackster35** [comment]
Is your issue fixed?

**Comment by techpulse** [comment]
yes

**Comment by Jackster35** [comment]
Press the close button ;)
