### ISSUE TITLE
how to make a custom gamemode? in Ogar.io, Need help!

### ISSUE THREAD

**Issue by theepicdeath100** [forairan/Ogar#80]
i'm having a issue with custom gamemode making, 
when im done making a file.js in gamemodes folder and start ogar.exe up when i type in 
"gamemode ID" it says Gamemode changing to free for all when i didnt change it to a ffa gamemode

thanks if you help! :+1:

**Comment by Jackster35** [comment]
Use https://github.com/forairan/Ogar/blob/master/src/gamemodes/HungerGames.js as a reference. It's nice to start from.

**Comment by theepicdeath100** [comment]
thanks will try 

btw very fast

**Comment by Ephemerality** [comment]
The exe is precompiled, so you can't edit the source and then run the exe unless you're recompiling it. You'd have to install Node and run it to get it to recognize your changes.  
To add a game mode, you need to add the new mode and add it to the index.js for the gamemodes.

**Comment by theepicdeath100** [comment]
how? do i install  "node" can you give me a link? :)

**Comment by Ephemerality** [comment]
https://nodejs.org/

**Comment by theepicdeath100** [comment]
thanks

**Comment by theepicdeath100** [comment]
Ephemerality how do you add it to the index.js 
sorry for any bugging

**Comment by Ephemerality** [comment]
In the game mode folder the index.js has a list of active game modes. You'd
need to copy the format the rest are in and add yours.

**Comment by theepicdeath100** [comment]
BvsW: require('./BvsW.js')?
case 16: //BvsW
			mode = new module.exports.blackvswhite();?

**Comment by maixuanhan** [comment]
yes. it's like that in gamemode/index.js. Remember `break;` statement also.

**Comment by theepicdeath100** [comment]
yes thx
