### ISSUE TITLE
[Question] Would there be anyway to run the server off a different website or client?

### ISSUE THREAD

**Issue by SacredMike** [forairan/Ogar#82]
See, with the agar.io server ips. It makes it a bit more difficult from connecting to each server. Instead of opening console and typing connect("x.x.x.x"). Instead of it basically creating a server on the website  just either host it on your own website or client?

**Comment by Ephemerality** [comment]
You can certainly clone the agar.io site onto a different web server and serve out a modified version that connects to your servers, but you may run into copyright issues for doing so.

**Comment by jollesnaas** [comment]
I can make it for you: Skype: jolle.snaas1
