### ISSUE TITLE
net::ERR_CONNECTION_TIMED_OUT

### ISSUE THREAD

**Issue by SMHDovydas** [forairan/Ogar#85]
When i try to connect to my server (with hamachi) it says this (btw i use google chrome) WebSocket connection to 'ws://25.116.142.156:443/' failed: Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT

**Comment by vram4** [comment]
If the server is on your own machine, use "ws://127.0.0.1:443/", not your hamachi address
