### ISSUE TITLE
Cant connect to my own server, help

### ISSUE THREAD

**Issue by natureflex** [forairan/Ogar#87]
connect("ws://xiaomiao.ddns.net:444","");
(index):52 Connecting to ws://xiaomiao.ddns.net:444
undefined
(index):52 WebSocket connection to 'ws://xiaomiao.ddns.net:444/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
(index):52 socket error
(index):53 socket close

i connect to my server using another computer and different connection...
I can only join local with my own pc or same connection with [connect("ws://127.0.0.1:444","");] or localhost:444]

**Comment by vram4** [comment]
Make sure your ports are forwarded.

**Comment by natureflex** [comment]
Port is forwarded for sure

**Comment by natureflex** [comment]
![image](https://cloud.githubusercontent.com/assets/13270061/8615491/8bcb87ca-2725-11e5-9483-701e84c2dd74.png)

**Comment by natureflex** [comment]
few days ago my friend still able to connect to my server, they cant connection after that until now...

**Comment by natureflex** [comment]
someone help please :<

**Comment by Ephemerality** [comment]
Just to clarify -- Are you trying to connect to a server that is hosted on the same compute or are you trying to access it from a different computer? If the server is running on the same computer you need to connect with 127.0.0.1 or localhost.  
Are you using the official Agar.io client or are you hosting one on a web server?

**Comment by natureflex** [comment]
Im trying to access it from a different computer also different connection

**Comment by natureflex** [comment]
my friend (different connection) cant join my server with the domain/ip

**Comment by Ephemerality** [comment]
> Are you using the official Agar.io client or are you hosting one on a web server?

**Comment by natureflex** [comment]
im using Agar.io client not on a web server, i just use that no-ip domain thingy to let my friend connect...

**Comment by Ephemerality** [comment]
You may want to see if the port is even accessible outside. You can use something like http://www.canyouseeme.org/ on the server to see if the port is being forwarded properly.

**Comment by natureflex** [comment]
yea it cant see me but...i did forwarding correct way...2 days ago it still working...but now...

**Comment by natureflex** [comment]
Owh= = what the hell i just checked my IPv4 it changed suddenly...
I think thats the problem...i'll give it a last try

**Comment by Ephemerality** [comment]
Dynamic IPs tend to do that sometimes.

**Comment by natureflex** [comment]
![image](https://cloud.githubusercontent.com/assets/13270061/8620140/24993284-2750-11e5-9f6a-a4978d1e6c40.png)

hmm? i checked with this port , and it cant see me...but why? I dint do any wrong on forwarding

**Comment by Ephemerality** [comment]
Was the server running for sure on port 543 when you checked it? If the server isn't running it will report it as closed.

**Comment by natureflex** [comment]
ok i'll check agian
