### ISSUE TITLE
changed port, still same?

### ISSUE THREAD

**Issue by techpulse** [forairan/Ogar#89]
i changed the port to 1337 and when i start it, it says port 443? 

[root@centos-agar src]# node index.js
[Game] Ogar - An open source Agar.io server implementation
[Game] Loaded stats server on port 88
[Game] Listening on port 443
[Game] Current game mode is Free For Al

![tdj1cv1](https://cloud.githubusercontent.com/assets/12190261/8617765/6ee4e96c-2707-11e5-9a0e-48c7ef91376c.png)

**Comment by techpulse** [comment]
tested on another server, same issue..

root@agario:~/Ogar/src# node index.js
[Game] Ogar - An open source Agar.io server implementation
[Game] Loaded stats server on port 88
[Game] Listening on port 443
[Game] Current game mode is Free For All
>


all i changed was max connections + port http://i.imgur.com/uflrvnf.png

**Comment by Ephemerality** [comment]
There are multiple .ini files provided, are you editing the one in the /src directory?

**Comment by techpulse** [comment]
no, only the one in the root

**Comment by techpulse** [comment]
thats new? i didnt do that before, happen after updating i guess

**Comment by Ephemerality** [comment]
That's the issue then. `root@agario:~/Ogar/src# node index.js`  
It all depends on what folder you're in when you launch Node.  
if you go back to the Ogar folder and run `node src` it will use the one in that folder instead.

**Comment by techpulse** [comment]
yeah works now, after i upated i can also not use http://dongsquad.pw/ (friend of mine sent this script) 

it lets me host copy of agar..

**Comment by Ephemerality** [comment]
See commit 4befbe169c8c920bed0328f3c161d46663d0d382

**Comment by techpulse** [comment]
thanks man i love you!
