### ISSUE TITLE
as I can change the appearance of the game?

### ISSUE THREAD

**Issue by listenyoumusic** [forairan/Ogar#91]
Hello, I would like to know as I can change the appearance of viruses and cells to avoid problems with agar.io.

And where customer is changed or ogar

Thanks, and sorry for my bad english. :)

**Comment by Ephemerality** [comment]
It sounds like you're asking if you can change the look of the game to avoid copyright infringement... The answer is probably no, but that's outside the scope of this project.

**Comment by listenyoumusic** [comment]
So I can have problems with agar.io?
