### ISSUE TITLE
If playerMaxCells is reached, viruses can be eaten.

### ISSUE THREAD

**Issue by Maxetto** [forairan/Ogar#93]
As the title says, if you reach the playerMaxCells and one of your cell is bigger than a virus, the next virus will be eaten (and works like a player) by the cell.

EDIT: Probably can be solved by swapping those 2 functions in the Virus.js:
```javascript
    // Cell consumes mass before splitting
    consumer.addMass(this.mass);

    // Cell cannot split any further
    if (numSplits <= 0) {
        return;
    }
```

**Comment by Ephemerality** [comment]
That's how it's supposed to work. When you eat a virus normally, you gain
its mass and split. If you can't split, you just gain its mass.

**Comment by Maxetto** [comment]
Wow, never heard that. It seems strange tho... You can eat a Virus without any issue :stuck_out_tongue:

**Comment by maixuanhan** [comment]
@Maxetto : I don't think your solution is right.

1. Eating Virus always gains mass. (current Ogar implementation)
 ```javascript
    // Cell consumes mass before splitting
    consumer.addMass(this.mass);

    // Cell cannot split any further
    if (numSplits <= 0) {
        return;
    }
 ```
2. Eating Virus does not gain mass at all.
 ```javascript
    // Cell consumes mass before splitting
    //consumer.addMass(this.mass);

    // Cell cannot split any further
    if (numSplits <= 0) {
        return;
    }
 ```
3. Eating Virus gains mass if player can still split.
 ```javascript
    // Cell cannot split any further
    if (numSplits <= 0) {
        return;
    }

    // Cell consumes mass before splitting
    consumer.addMass(this.mass);
 ```
4. Eating Virus gains mass if player cannot split any more.
 ```javascript
    // Cell cannot split any further
    if (numSplits <= 0) {
        // Cell consumes mass
        consumer.addMass(this.mass);
        return;
    }

 ```

It seem that on vanilla, the second case is applied (Virus is not yummy). I cannot verify. I tried on vanilla (many times) but I died before I could confirm that behavior. People played so well.

**Comment by Ephemerality** [comment]
When you eat a virus in vanilla, you gain its mass. Try eating a virus of
100 mass when you hit around 130ish, you'll split into 8 pieces of around
29 (if you were 132), meaning your total is 232.

**Comment by vram4** [comment]
As far as i know, you gain mass when you eat a virus, but only in ffa/experimental. There are lots of videos on youtube showing this feature.

**Comment by Agarian** [comment]
This is historic

**Comment by firelightning13** [comment]
lol why we are even here

**Comment by Agarian** [comment]
idk
