### ISSUE TITLE
freeze on linux

### ISSUE THREAD

**Issue by techpulse** [forairan/Ogar#94]
i keep freezing, so do my members.. im using debian

**Comment by Ephemerality** [comment]
Had you typed in any commands? From my experience, that's the only time I had any freezing. Then as I typed, players would move again until I stopped typing.

**Comment by techpulse** [comment]
no commands other than playerlist a few times... others plays fine, till they reach certain limit i think ?

**Comment by vram4** [comment]
Fixed in 6306800ccefd88723e1304031eec02e9448f3a69
