### ISSUE TITLE
Change Color always get Black color result

### ISSUE THREAD

**Issue by helma27** [forairan/Ogar#96]
Hello, when i use command to change color, why i always get black color?
i type in console: "color <id> red", result is black color..
Do i miss something?

**Comment by Gjum** [comment]
The [command]https://github.com/forairan/Ogar/blob/92ddf34eafa461410961e17c6dd63f7d511df6d6/README.md#console-commands() is:

> Color [Player ID] [Red] [Green] [Blue]

So `Color 255 0 0` would be red.

**Comment by helma27** [comment]
Oh i see!
Thanks for helping! :)
