### ISSUE TITLE
I have an error when i command "npm install ./Ogar"

### ISSUE THREAD

**Issue by Ganggroid** [forairan/Ogar#97]
![image](https://cloud.githubusercontent.com/assets/5188404/8636927/ee86cc40-28b4-11e5-9396-38dc8989cf28.png)
what can i do for this error?

**Comment by anonprophet** [comment]
npm install ws

**Comment by Ganggroid** [comment]
Thanks.

**Comment by Ganggroid** [comment]
https://www.nginx.com/blog/websocket-nginx/
